trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Azure Kubernetes Terraform Provisioning Started
  displayName: 'Azure Kubernetes Cluster'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure-devops-terraform-prov.pub'

- task: TerraformCLI@0
  name: Terraform_Init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aks'
    backendType: 'azurerm'
    backendServiceArm: 'ARM-Service'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'aksterraformbackend'
    backendAzureRmContainerName: 'terraform-state'
    backendAzureRmKey: 'aks-terraform-state'

- task: TerraformCLI@0
  name: Terraform_Apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aks'
    environmentServiceName: 'ARM-Service'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'